### ISSUE TITLE
Build a version with all available plugins

### ISSUE THREAD

**Issue by probonopd** [ecmu/geany.AppImage#2]
Someone on Twitter is asking for a (separate) version with all available [plugins](https://github.com/geany/geany-plugins) so that they work out of the box without having to install anything.

https://twitter.com/app4soft/status/1080983598235303937

**Comment by ecmu** [comment]
Ok, I will look at it...

**Comment by ecmu** [comment]
I included the plugins into the AppImage. Is it OK for you ?

**Comment by probonopd** [comment]
Great, thank you very much :+1:
