### ISSUE TITLE
Geany "forgets" which plugins are active when closed

### ISSUE THREAD

**Issue by nixbody** [ecmu/geany.AppImage#5]
Geany keeps the list of active plugins in it's configuration file located at `~/.config/geany/geany.conf`. The problem is that the list of active plugins consists of absolute paths to corresponding `.so` files which reside inside the AppImage and these paths become invalid when the app quits and its filesystem is unmounted.

**Comment by ecmu** [comment]
I also don't know how this old AppImage from AppRepo.de was built and still think this should be handled by the Geany development team.

However, I did a (dirty) workaround and pushed a new version of Geany 1.38.0
